CREATE DATABASE EMPLOYEE_DETAIL
USE EMPLOYEE_DETAIL

CREATE TABLE EMPLOYEE_TABLE( 
  EMPID INT PRIMARY KEY,
  FIRSTNAME VARCHAR(50),
  LASTNAME VARCHAR(50),
  SALARY FLOAT,
  JOININGDATE DATE,
  DEPARTMENT VARCHAR(50),
  GENDER VARCHAR(10)
);

SELECT *FROM EMPLOYEE_TABLE

INSERT INTO EMPLOYEE_TABLE VALUES (1,'VIKAS','ALHAWAT',600000,'2013-12-02','IT','MALE');
INSERT INTO EMPLOYEE_TABLE VALUES (2,'NIKITA', 'JAIN',530000,'2013-02-14','HR','FEMALE');
INSERT INTO EMPLOYEE_TABLE VALUES (3,'ASHISH','KUMAR',1000000,'2013-02-14','IT','MALE');
INSERT INTO EMPLOYEE_TABLE VALUES (4,'NIKHIL','SHARMA',480000,'2013-02-15','HR','MALE');
INSERT INTO EMPLOYEE_TABLE VALUES (5,'ANISH','KAIDAN',500000,'2013-02-16','PAYROLL','MALE');

SELECT *FROM EMPLOYEE_TABLE;
SELECT FIRSTNAME FROM EMPLOYEE_TABLE;
SELECT UPPER(FIRSTNAME) AS "First Name" FROM EMPLOYEE_TABLE;
SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) AS "Name" FROM EMPLOYEE_TABLE;
SELECT * FROM EMPLOYEE_TABLE WHERE FIRSTNAME = 'VIKAS';
SELECT * FROM EMPLOYEE_TABLE WHERE FIRSTNAME LIKE 'a%';
SELECT * FROM EMPLOYEE_TABLE WHERE FIRSTNAME LIKE 'a%';
SELECT * FROM EMPLOYEE_TABLE WHERE FIRSTNAME LIKE '%h';
SELECT * FROM EMPLOYEE_TABLE WHERE FIRSTNAME NOT LIKE '[a-p]%';
SELECT * FROM EMPLOYEE_TABLE WHERE GENDER LIKE 'le' AND GENDER = 'MALE';
SELECT * FROM EMPLOYEE_TABLE WHERE FIRSTNAME LIKE 'A____';
SELECT * FROM EMPLOYEE_TABLE WHERE FIRSTNAME LIKE '%[%]%';
SELECT DISTINCT DEPARTMENT FROM EMPLOYEE_TABLE;
SELECT MAX(SALARY) FROM EMPLOYEE_TABLE;
SELECT MIN(SALARY) FROM EMPLOYEE_TABLE;
SELECT FORMAT(JOININGDATE, '%d %b %Y') FROM EMPLOYEE_TABLE;
SELECT FORMAT(JOININGDATE, '%Y/%m/%d') FROM EMPLOYEE_TABLE;
SELECT CONVERT(time, JOININGDATE) FROM EMPLOYEE_TABLE;
SELECT YEAR(JOININGDATE) FROM EMPLOYEE_TABLE;
SELECT MONTH(JOININGDATE) FROM EMPLOYEE_TABLE;
SELECT GETDATE();
SELECT GETUTCDATE();
SELECT FIRSTNAME, GETDATE(), JOININGDATE, DATEDIFF(MONTH, JOININGDATE, GETDATE()) AS MonthsDiff FROM EMPLOYEE_TABLE;
SELECT FIRSTNAME, GETDATE(), JOININGDATE, DATEDIFF(DAY, JOININGDATE, GETDATE()) AS DaysDiff FROM EMPLOYEE_TABLE;
SELECT * FROM EMPLOYEE_TABLE WHERE YEAR(JOININGDATE) = 2013;
SELECT * FROM EMPLOYEE_TABLE WHERE MONTH(JOININGDATE) = 1;
SELECT * FROM EMPLOYEE_TABLE WHERE MONTH(JOININGDATE) = 1;
SELECT COUNT(*) FROM EMPLOYEE_TABLE;
SELECT TOP 1 * FROM EMPLOYEE_TABLE;
SELECT * FROM EMPLOYEE_TABLE WHERE FIRSTNAME IN ('VIKAS', 'ASHISH', 'NIKHIL');
SELECT * FROM EMPLOYEE_TABLE WHERE FIRSTNAME NOT IN ('VIKAS', 'ASHISH', 'NIKHIL');
SELECT RTRIM(FIRSTNAME) FROM EMPLOYEE_TABLE;
SELECT LTRIM(FIRSTNAME) FROM EMPLOYEE_TABLE;
SELECT FIRSTNAME, CASE WHEN GENDER = 'MALE' THEN 'M' ELSE 'F' END AS Gender FROM EMPLOYEE_TABLE;
SELECT CONCAT('Hello ', FIRSTNAME) FROM EMPLOYEE_TABLE;
SELECT * FROM EMPLOYEE_TABLE WHERE SALARY > 600000;
SELECT * FROM EMPLOYEE_TABLE WHERE SALARY < 700000;
SELECT * FROM EMPLOYEE_TABLE WHERE SALARY BETWEEN 500000 AND 600000;


CREATE DATABASE PROJECT_DETAIL

CREATE TABLE PROJECT_DETAIL (
ProjectDetailID INT PRIMARY KEY,
EmployeeDetailID INT,
ProjectName VARCHAR (50)
);

SELECT *FROM PROJECT_DETAIL

Insert into PROJECT_DETAIL values(1,1,'Task track')
Insert into PROJECT_DETAIL values(2,1,'CLP')
Insert into PROJECT_DETAIL values(3,1,'SURVEY MANAGEMENT')
Insert into PROJECT_DETAIL values(4,2,'HR TRACK')
Insert into PROJECT_DETAIL values(5,3,'TASK TRACK')
Insert into PROJECT_DETAIL values(6,3,'GRS')
Insert into PROJECT_DETAIL values(7,3,'DDS')
Insert into PROJECT_DETAIL values(8,4,'HR MANAGEMENT')
Insert into PROJECT_DETAIL values(9,6,'GL MANAGEMENT')

SELECT * FROM PROJECT_DETAIL;

SELECT DEPARTMENT, SUM(SALARY) AS TotalSalary
FROM EMPLOYEE_TABLE
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, SUM(SALARY) AS TotalSalary
FROM EMPLOYEE_TABLE
GROUP BY DEPARTMENT
ORDER BY TotalSalary ASC;

SELECT DEPARTMENT, SUM(SALARY) AS TotalSalary
FROM EMPLOYEE_TABLE
GROUP BY DEPARTMENT
ORDER BY TotalSalary DESC;

SELECT DEPARTMENT, COUNT(*) AS TotalDepartments, SUM(SALARY) AS TotalSalary
FROM EMPLOYEE_TABLE
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, AVG(SALARY) AS AverageSalary
FROM EMPLOYEE_TABLE
GROUP BY DEPARTMENT
ORDER BY AverageSalary ASC;

SELECT DEPARTMENT, MAX(SALARY) AS MaxSalary
FROM EMPLOYEE_TABLE
GROUP BY DEPARTMENT
ORDER BY MaxSalary ASC;

SELECT DEPARTMENT, MIN(SALARY) AS MinSalary
FROM EMPLOYEE_TABLE
GROUP BY DEPARTMENT
ORDER BY MinSalary ASC;

SELECT EMPLOYEE_TABLE.FIRSTNAME, PROJECT_DETAIL.ProjectName
FROM EMPLOYEE_TABLE
INNER JOIN PROJECT_DETAIL ON EMPLOYEE_TABLE.EMPID = PROJECT_DETAIL.EmployeeDetailID;

SELECT EMPLOYEE_TABLE.FIRSTNAME, PROJECT_DETAIL.ProjectName
FROM EMPLOYEE_TABLE
INNER JOIN PROJECT_DETAIL ON EMPLOYEE_TABLE.EMPID = PROJECT_DETAIL.EmployeeDetailID;

SELECT EMPLOYEE_TABLE.FIRSTNAME, ISNULL(PROJECT_DETAIL.ProjectName, '-No Project Assigned') AS ProjectName
FROM EMPLOYEE_TABLE
LEFT JOIN PROJECT_DETAIL ON EMPLOYEE_TABLE.EMPID = PROJECT_DETAIL.EmployeeDetailID;

SELECT EMPLOYEE_TABLE.FIRSTNAME, ISNULL(PROJECT_DETAIL.ProjectName, '-No Project Assigned') AS ProjectName
FROM EMPLOYEE_TABLE
LEFT JOIN PROJECT_DETAIL ON EMPLOYEE_TABLE.EMPID = PROJECT_DETAIL.EmployeeDetailID;

SELECT EMPLOYEE_TABLE.FIRSTNAME, ISNULL(PROJECT_DETAIL.ProjectName, '-No Project Assigned') AS ProjectName
FROM PROJECT_DETAIL
LEFT JOIN EMPLOYEE_TABLE ON EMPLOYEE_TABLE.EMPID = PROJECT_DETAIL.EmployeeDetailID;

SELECT EMPLOYEE_TABLE.FIRSTNAME, PROJECT_DETAIL.ProjectName
FROM EMPLOYEE_TABLE
FULL JOIN PROJECT_DETAIL ON EMPLOYEE_TABLE.EMPID = PROJECT_DETAIL.EmployeeDetailID;

SELECT EMPLOYEE_TABLE.FIRSTNAME, PROJECT_DETAIL.ProjectName
FROM EMPLOYEE_TABLE
FULL JOIN PROJECT_DETAIL ON EMPLOYEE_TABLE.EMPID = PROJECT_DETAIL.EmployeeDetailID;

SELECT EMPLOYEE_TABLE.FIRSTNAME, PROJECT_DETAIL.ProjectName
FROM EMPLOYEE_TABLE
INNER JOIN (
    SELECT EmployeeDetailID
    FROM PROJECT_DETAIL
    GROUP BY EmployeeDetailID
    HAVING COUNT(*) > 1
) AS sub ON EMPLOYEE_TABLE.EMPID = sub.EmployeeDetailID
INNER JOIN PROJECT_DETAIL ON EMPLOYEE_TABLE.EMPID = PROJECT_DETAIL.EmployeeDetailID;

SELECT EMPLOYEE_TABLE.FIRSTNAME, PROJECT_DETAIL.ProjectName
FROM EMPLOYEE_TABLE
INNER JOIN PROJECT_DETAIL ON EMPLOYEE_TABLE.EMPID = PROJECT_DETAIL.EmployeeDetailID
INNER JOIN (
    SELECT ProjectName
    FROM PROJECT_DETAIL
    GROUP BY ProjectName
    HAVING COUNT(*) > 1
) AS sub ON PROJECT_DETAIL.ProjectName = sub.ProjectName;

SELECT EMPLOYEE_TABLE.FIRSTNAME, PROJECT_DETAIL.ProjectName
FROM EMPLOYEE_TABLE
CROSS JOIN PROJECT_DETAIL;






































